### ISSUE TITLE
Login via Runkeeper is broken

### ISSUE THREAD

**Issue by Dumbaz** [criticalmass-one/criticalmass-in#237]
The `Login via Runkeeper` button, which leads to https://criticalmass.in/login/runkeeper is broken.

I get redirected to `https://runkeeper.com/apps/authorize?response_type=code&client_id=12345&redirect_uri=https%3A%2F%2Fcriticalmass.in%2Flogin%2Fcheck-runkeeper` and get a http 500 server error.

`Failed to load resource: the server responded with a status of 500 ()`

Tested with Chrome and Safari.
Reason might be DSGVO

**Comment by maltehuebner** [comment]
Thanks for your report, I’ll check that later.

By the way, it looks like you are the first one ever trying to log in via runkeeper, so I cannot assure it was working before GDPR ;-)

**Comment by maltehuebner** [comment]
As Runkeeper is not supported anymore and discontinued any api access, I’ll close this issue.
