### ISSUE TITLE
Authorize with Strava broken

### ISSUE THREAD

**Issue by nv1t** [criticalmass-one/criticalmass-in#552]
I tried to authorize criticalmass.in in strava. my account is created (and logged in) with another oauth event, and i never authorized strava before.

i get an error message: 
```json
{"message":"Bad Request","errors":[{"resource":"Authorize","field":"scope","code":"invalid"}]}
```
![2019-10-25-235832_1439x280_scrot](https://user-images.githubusercontent.com/1524118/67607198-f124ad80-f783-11e9-8d37-64eb68966813.png)

Authorizing a fresh account results in a 500 error.
![2019-10-26-000155_956x298_scrot](https://user-images.githubusercontent.com/1524118/67607190-e8cc7280-f783-11e9-94d6-93d6e5e351a4.png)

**Comment by maltehuebner** [comment]
Thank you for dropping this issue. Could you please try to login again if I just solved this problem with #554? The "old" strava oauth process was faded out by mid October and I didn’t manage to get everything done in time.
