### ISSUE TITLE
"Turnus manuell auslösen" broken - HTTP 500

### ISSUE THREAD

**Issue by ossie** [criticalmass-one/criticalmass-in#744]
**Current behaviour**
Pressing "Turnus manuell auslösen" leads to an Internal Server Error (500). 

**Reproduction**
Press "Turnus manuell auslösen" on https://criticalmass.in/wetter-ruhr/cycles/list
![grafik](https://user-images.githubusercontent.com/462735/93982425-83ad4280-fd81-11ea-8d13-8b7b0a2b17a2.png)

**Comment by maltehuebner** [comment]
Danke für deine Meldung — Ich hatte gehofft, das noch reparieren zu können, bevor es jemand merkt ;-)

Ich hatte vor ein paar Wochen den so genannten Ride-Generator in einen eigenen Service ausgelagert (#720), mit dem die eigentliche Critical-Mass-Anwendung sprechen kann, aber der Ride-Generator ist noch gar nicht als eigener Service deployed wurden. Das muss ich dringend nachholen, schließlich neigt sich der Monat langsam dem Ende zu und es gibt für den nächsten Monat noch keine Touren.

Ich versuche das heute im Laufe des Tages einzurichten.

**Comment by ossie** [comment]
Jetzt scheint es so zu funktionieren, wie es soll. Besten Dank!

**Comment by ossie** [comment]
Funktioniert das Setzen des Turnus problemlos? Entweder wurden hier https://criticalmass.in/wetter-ruhr/list die Uhrzeiten ausgewürfelt. Oder irgendwer hat die Uhrzeiten angepasst. Kann das nachverfolgt werden?

**Comment by maltehuebner** [comment]
Jetzt sollte es funktionieren — es gab da noch ganz erhebliche Probleme mit der Zeitumstellung und verschiedenen Zeitzonen, die nun behoben sein sollten. Die bereits existierenden Touren müssen leider manuell korrigiert werden — aber dafür habe ich ja nun im November Zeit genug ;-)

**Comment by ChrizKu** [comment]
In Schorndorf gab ich auch 18:00 beim Turnus an, der Generator macht daraus

Critical Mass Schorndorf 25.06.2021 | Friday, 25. June 2021 | 16:00 Uhr | Marktplatz Schorndorf
-- | -- | -- | --
Critical Mass Schorndorf 30.07.2021 | Friday, 30. July 2021 | 16:00 Uhr | Marktplatz Schorndorf
Critical Mass Schorndorf 27.08.2021 | Friday, 27. August 2021 | 16:00 Uhr | Marktplatz Schorndorf
Critical Mass Schorndorf 24.09.2021 | Friday, 24. September 2021 | 16:00 Uhr | Marktplatz Schorndorf
Critical Mass Schorndorf 29.10.2021 | Friday, 29. October 2021 | 16:00 Uhr | Marktplatz Schorndorf
Critical Mass Schorndorf 26.11.2021 | Friday, 26. November 2021 | 17:00 Uhr | Marktplatz Schorndorf
Critical Mass Schorndorf 31.12.2021 | Friday, 31. December 2021 | 17:00 Uhr | Marktplatz Schorndorf

**Comment by ChrizKu** [comment]
Beim Erstellen einer [Serie für die Vergangenheit](https://criticalmassschorndorf.wordpress.com/) kommt auch ein Fehler – was ist falsch?
![grafik](https://user-images.githubusercontent.com/12224796/122619630-27b5e700-d091-11eb-97cc-af55e6ba13fb.png)

**Comment by ChrizKu** [comment]
nach welcher Zeit werden automatisch aus dem Turnus Touren erzeugt?
ich würde gern zur Ausfahrt verlinken auf Socialmedia…

**Comment by maltehuebner** [comment]
Hej @ChrizKu,

ich habe die Probleme mit den Zeitzonen jetzt repariert und hoffe, dass es jetzt wieder funktioniert. Ich muss gestehen, dass ich am „Endgegner Zeitzone“ immer wieder scheitere und eine Überprüfung auf die jeweilige Zeitzone an vielen Stellen der Anwendung fehlt, so dass dort einfach UTC gewählt wird — dadurch sind die Uhrzeiten jeweils eine oder zwei Stunden verschoben.

Das Problem mit dem Anlegen von Touren in der Vergangenheit liegt daran, dass es keinen 31. November gibt — wenn du den 30. November anwählst, sollte es funktionieren.

Dass die Touren „automatisch“ angelegt werden, ist eigentlich eine dreiste Lüge, in Wirklichkeit muss ich regelmäßig den Tourengenerator manuell anschmeißen. Ich habe jetzt eben die Touren für Juli und August hinzugefügt und herrje, ich hoffe, jetzt hat die Sache mit den Zeitzonen einigermaßen funktioniert.
