### ISSUE TITLE
Wikimedia map tiles will be discontinued

### ISSUE THREAD

**Issue by camelCaseNick** [criticalmass-one/criticalmass-in#748]
According to <https://lists.wikimedia.org/pipermail/maps-l/2020-August/001729.html> the serving of Wikimedia map tiles to third-parties will be discontinued in about two weeks. And they are used here through the <https://github.com/calderacc/tilecache> cache.

**Comment by maltehuebner** [comment]
Thank you for dropping this issue. I currently have another tile cache running at my server, but as I don’t have the time for running an own tile server, I switched to stadia maps, which offer a lot of map views for an affordable price — and the map tiles look quite similar to Wikimedia's.
