### ISSUE TITLE
Registration not working (no confirmation mail sent)

### ISSUE THREAD

**Issue by Splines** [criticalmass-one/criticalmass-in#749]
Hi, I've tried to register for [criticalmass.in](https://criticalmass.in), however no registration e-mail seems to be sent to me (spam folder already checked of course). I've tried this with two different e-mails, each time with the same problem. Help appreciated since I can't login without having confirmed my account.

**Comment by maltehuebner** [comment]
Too bad — I got a lot of difficulties with my mail server and the dns settings to get the mail service running in the last months and hoped to got everything configured correctly now. Could you please drop a short mail to criticalmass@caldera.cc with those rejected e-mail addresses?

**Comment by maltehuebner** [comment]
This issue is solved since we got rid of SwiftMailer and registration mails.
