### ISSUE TITLE
"Mehr erfahren" Not found 404

### ISSUE THREAD

**Issue by Ordinateur-Hack** [criticalmass-one/criticalmass-in#750]
Go to https://criticalmass.in/ and click on the button "Mehr erfahren" in the top image (next to the button "Städte")
https://criticalmass.in/content/what-is-the-mass returns 404.

**Comment by maltehuebner** [comment]
Thank’s for your message. I guess the old link to the help page sneaked in while reordering the teaser images some weeks ago. I setup the right link now.

**Comment by ChrizKu** [comment]
still 404 :P
