### ISSUE TITLE
Error 500 for some meeting point pages

### ISSUE THREAD

**Issue by givemeallyourspam** [criticalmass-one/criticalmass-in#804]
Some Treffpunkt pages (e.g. next month's Magellanterassen, Marco-Polo-Terassen, Deichtorhallen and others) return an error 500: https://criticalmass.in/hamburg/location/marco-polo-terrassen

Other pages work fine.

Issue found on Firefox for Android and

**Comment by maltehuebner** [comment]
Thank you — should be fixed now.
