### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by mega-stoffel** [criticalmass-one/criticalmass-in#817]
Hej!
I can't insert the number of participants for the Stuttgart CM on May 6th. After entering the number and pressing on "Speichern" the 500 error shows up.
The same, after I select my track from Strava for this day - also a 500 internal server error:

```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

**Comment by c-schmitz** [comment]
The 500 errors are very persistent across the page.

**Comment by maltehuebner** [comment]
Thank you for addressing this issue. It looks like those problems occur after an update of some dependencies. I have already fixed some of those problems :-/
