### ISSUE TITLE
Add Fediverse / Mastodon as network option in social networks

### ISSUE THREAD

**Issue by foss-** [criticalmass-one/criticalmass-in#920]
**Currently**
When adding Fediverse account it shows as `Homepage`.

**Expected**
Would be great if Fediverse accounts were recognized and named as `Fediverse`.

PR to cover mastodon: https://github.com/criticalmass-one/criticalmass-in/pull/906

**Comment by maltehuebner** [comment]
Pull Request #906 is going live with next release.

**Comment by foss-** [comment]
Mastodon is now an option in the social networks settings 🙌
