### ISSUE TITLE
500 Server Error for "Impressum" and "Datenschutz"

### ISSUE THREAD

**Issue by MaxMalRichtig** [criticalmass-one/criticalmass-in#922]
When opening the pages:

- Impressum: https://criticalmass.in/content/impress
- Datenschutz: https://criticalmass.in/content/privacy

the server returns a "500 Internal Server Error".

**Comment by maltehuebner** [comment]
Thank you for your message. The impress data is loaded from http://maltehuebner.de/malte.json to have a single point of truth when moving to another address or city and it looks like the json file was broken. It is fixed now.
