### ISSUE TITLE
can't view own tracks

### ISSUE THREAD

**Issue by foss-** [criticalmass-one/criticalmass-in#948]
After logging in, when selecting `Benutzerkonto > Deine Tracks` landing on `https://criticalmass.in/track/list` showing error `The server returned a "500 Internal Server Error".`

Unsure if this worked prior to today's update.

Oh and hanks for the recent update. Was very happy to see activity ❤️ 💪 🚲

**Comment by maltehuebner** [comment]
Thank you for your report. I forgot to implement a ```hasRole()``` method after removing FosUserBundle in #904. It is fixed now with #954.

And yes, I’m also very happy to got rid of a big bunch of old legacy code which blocked any kind of development for years!

**Comment by foss-** [comment]
Confirmed - thank you 👍
