### ISSUE TITLE
opening any specific tour on firefox on android results in "500 Internal Server Error"

### ISSUE THREAD

**Issue by foss-** [criticalmass-one/criticalmass-in#950]
Curiously while on desktop, loading specific rides works as expected in Firefox, loading any tour on Android + Firefox results in `500 Internal Server Error`.

This has been reproduced on two different devices.

Android 13.1, Firefox 128.0.1

**Comment by maltehuebner** [comment]
Thank you for your bug report. Looks like I wasn’t running the tests after last deployment. It should be fixed now.

**Comment by foss-** [comment]
Confirming the fix does the trick. I am now able to load rides as expected on mobile Android with Firefox. Thanks for the superquick fix 🙏 ❤️
