### ISSUE TITLE
Add additional `datetime` field to carry timezone information

### ISSUE THREAD

**Issue by mltbnz** [criticalmass-one/criticalmass-in#979]
Suggestion: 

To make the ride feature more versatile for international events I think it would be beneficial to introduce a new field for the `datetime` of the event that carries information about the timezone like f.ex. an `ISO8601` String.

I was trying to add this in [criticalmaps-ios](https://github.com/criticalmaps/criticalmaps-ios) but it was giving me a hard time 😆

**Comment by maltehuebner** [comment]
If you call the api like https://criticalmass.in/api/ride?year=2024&month=9&size=500&extended=true, the {{datetime}} property is an UTC timestamp and via the {{city}} property, you get access to {{timezone}}. Can you work with that data?

**Comment by mltbnz** [comment]
thanks. that should be helpful 😃 🎉 

In the request you referenced I see a ride in lisbon with the timezone `"Europe/Berlin"`.
Is this something someone creating the event is setting? 

Besides that I see different timezones like for a ride in London f.ex. 👍 

<details><summary>Details</summary>
<p>

```json
{
    "city": {
        "description": "Massa Cr\u00edtica Lisboa | every last Friday of the month | 6pm | Marqu\u00eas de Pombal\r\nLisBora | every Tuesday | 8pm | Saldanha",
        "id": 748,
        "latitude": 38.725977097001,
        "longitude": -9.1505663398857,
        "main_slug": {
            "id": 10356,
            "slug": "lisboa"
        },
        "name": "Lisboa",
        "slugs": [
            {
                "id": 10356,
                "slug": "lisboa"
            }
        ],
        "timezone": "Europe/Berlin",
        "title": "Lisboa"
    },
    "cycle": {
        "day_of_week": 2,
        "latitude": 38.733125369076,
        "location": "Monumento ao Duque da Saldenha",
        "longitude": -9.144852811005,
        "week_of_month": 4
    },
    "date_time": 1727204400,
    "enabled": true,
    "id": 20211,
    "latitude": 38.733125369076,
    "location": "Monumento ao Duque da Saldenha",
    "longitude": -9.144852811005,
    "social_network_profiles": [],
    "title": "Lisboa 24.09.2024"
}
```

</p>
</details>

**Comment by mltbnz** [comment]
Closing this since using the extended response seems to solve the issue

For reference

https://github.com/criticalmaps/criticalmaps-ios/pull/511
